### ISSUE TITLE
Need help building from this example

### ISSUE THREAD

**Issue by DanielBajoCollados** [dominikbelter/ompl_example_2d#6]
I'm trying to make a new package following this example. The example itself work great, but when trying to replicate it i get the following error.
In the planPath function (What in mine I called it pathPlanner), after I include the line `auto si(std::make_shared<ob::SpaceInformation>(space)` i get the following error when building:
`undefined reference to 'ompl::base::SpaceInformation::SPaceInformation(std::shared_ptr<ompl::base::StateSpace>)'`
The main difference between your code and the one I'm making is that I'm doing everything inside a single .cpp file, instead of making a library and then using it.
Besides that, my CMakeLists.txt and package.xml are the same (with the changes that come form not having a separate files)
I've looked at the error online, but none of the answers helped me, so I was wondering if you have faced the same error while making this example, and if so, how did you fix it?

**Comment by dominikbelter** [comment]
Did you remember to add OMPL_LIBRARIES when building your executable? Here is the example from CMakelists.txt:
target_link_libraries(ompl_example_2d_node ${PROJECT_NAME}_library ${OMPL_LIBRARIES})
BTW, I recommend keeping separate files. It will help you when your project becomes large.

**Comment by DanielBajoCollados** [comment]
Yeah, that was the problem. Thank you very much and sorry for the bother. I'll do everything in more files eventually, for the moment I was just trying stuff out.

**Comment by dominikbelter** [comment]
Perfect!
